### ISSUE TITLE
cannot compile on s390x with native redhat gcc 10

### ISSUE THREAD

**Issue by tseeling** [skarnet/s6-linux-utils#1]
I don't have sys/random.h, but it compiles if I remove the line.

**Comment by skarnet** [comment]
[https://man7.org/linux/man-pages/man2/getrandom.2.html](https://man7.org/linux/man-pages/man2/getrandom.2.html) says:

`getrandom() was introduced in version 3.17 of the Linux kernel. Support was added to glibc in version 2.25.`

glibc-2.25 was released on February of 2017. We are now at glibc-2.36, and a high number of bugfixes, including security issues, have been made in recent versions.

If your toolchain doesn't even target glibc-2.25, it is *ancient*, and may put your product at risk. I would raise an alarm with your security team, and try and get a more recent toolchain.

**Comment by tseeling** [comment]
s390x Linux is delivered by Redhat so I have to rely on their diligence on backporting security fixes.

I will try to compile the packages on a machine with RHEL 8.
Thanks for the hint.

```
$ uname -r
4.18.0-372.26.1.el8_6.s390x
$ /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.28.
```

**Comment by skarnet** [comment]
Good luck.
